### PR TITLE
Support SVG output

### PR DESCRIPTION
**Pull request by zengxs**
Support render to SVG image

### CODE REVIEW

**Comment by jihchi** [comment]
Awesome! Thanks for the PR.

Would you mind to add a few tests?

**Comment by zengxs** [comment]
@jihchi
I'm not good at NodeJS & supertest, but I tried to write some test code.
Hope this will be useful.

**Comment by jihchi** [comment]
Thanks a lot! @zengxs

**Comment by jihchi** [comment]
FYI @zengxs

mermaid.ink has been deployed and now you are able to get the SVG output!

For example:
svg

**Pull request merged**
