### PR TITLE
Use chromium on docker

### PR DESCRIPTION
**Pull request by maxstanley**
- Fixes Docker image, currently fails to start.
- Updates the Dockerfile to be inline with the puppeteer example.
- Replaces Google Chrome with Chromium
  - This enables the container to be built and run on non-x86 platforms.
- Reduces the final image size by 500MB
- Always build Docker image in CI, but only push on tag

Happy to make any changes!

### CODE REVIEW

**Comment by jihchi** [comment]
@maxstanley  Thank you for the contribution!

> Fixes Docker image, currently fails to start.

Could you please share the error message?

**Comment by maxstanley** [comment]
```bash
$ docker run --rm -it -e 'NODE_OPTIONS="--max-http-header-size=102400000"' -p 3000:3000 ghcr.io/jihchi/mermaid.ink:v8.1.0

> mermaid.ink@8.1.0 start /usr/src/app
> node src/index.js

Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[30:30:1227/110607.008562:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Operation not permitted (1)
*** caught exception ***
Error: Failed to launch the browser process!
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
[30:30:1227/110607.008562:FATAL:zygote_host_impl_linux.cc(201)] Check failed: . : Operation not permitted (1)


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at ChildProcess.onClose (/usr/src/app/node_modules/.pnpm/@puppeteer+browsers@1.8.0/node_modules/@puppeteer/browsers/lib/cjs/launch.js:271:24)
    at ChildProcess.emit (node:events:529:35)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by jihchi** [comment]
Could you please try to add `--cap-add=SYS_ADMIN` to the `docker run`?

**Comment by maxstanley** [comment]
It works. But spits out a few other things that can probably be ignored?

```bash
$ docker run --rm -it -e 'NODE_OPTIONS="--max-http-header-size=102400000"' -p 3000:3000 --cap-add=SYS_ADMIN ghcr.io/jihchi/mermaid.ink:v8.1.0

> mermaid.ink@8.1.0 start /usr/src/app
> node src/index.js

[30:58:1227/131142.909298:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[30:62:1227/131143.045894:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[30:62:1227/131143.045967:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[30:58:1227/131143.049121:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[30:58:1227/131143.049277:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[30:58:1227/131143.049314:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[30:58:1227/131143.049356:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[30:58:1227/131143.064870:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[30:58:1227/131143.064912:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

DevTools listening on ws://127.0.0.1:46743/devtools/browser/5ba0e344-c543-49aa-ac5a-e70a4dd0b3c8
[30:123:1227/131143.144286:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[30:123:1227/131143.144346:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[30:123:1227/131143.144431:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[30:123:1227/131143.144485:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[30:123:1227/131143.144520:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[103:7:1227/131143.160910:ERROR:command_buffer_proxy_impl.cc(127)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

A different option could be to run chrome with `--no-sandbox`? I would probably not use this image if I had to run it with `--cap-add=SYS_ADMIN` due to the security implications.

**Comment by maxstanley** [comment]
The following diff allows me to use the original docker run command.

```
diff --git a/src/app.js b/src/app.js
index 5fa85e2..7207168 100644
--- a/src/app.js
+++ b/src/app.js
@@ -36,6 +36,7 @@ async function setup() {
     },
     // https://peter.sh/experiments/chromium-command-line-switches/
     args: [
+      '--no-sandbox',
       '--disable-background-timer-throttling',
       '--disable-backgrounding-occluded-windows',
       '--disable-breakpad',
```

The other this PR solves is allowing the container to be built on ARM, currently having to run these tests on a remote VM :)

**Comment by maxstanley** [comment]
This <https://stackoverflow.com/q/76833201> is quite a nice TLDR of the options available for running Chrome in a container.

The choice of this PR was to "use a different browser" in this case chromium, so that it could run in the container as a non-root user and adds support for non-x86 targets.

**Comment by jihchi** [comment]
I see the advantage of supporting for non-x86 targets, but I'm cautious about shifting to Chromium since I aim for [mermaid.ink](https://mermaid.ink) to provide mermaid diagrams that are as accurate as those produced with the [Mermaid Live Editor](https://mermaid.live/edit).

As for sandboxing, the [troubleshooting document](https://pptr.dev/troubleshooting#setting-up-chrome-linux-sandbox) from puppeteer advise against running the browser without a sandbox and provide some options to configure it properly, I'll look into that in more details.

**Comment by maxstanley** [comment]
All makes sense. Let me know if I can help with anything 😃

**Pull request closed without merging**
